In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing 
%matplotlib inline


In [2]:
df=pd.read_csv("C:\\Users\\JoseMaría\\Documents\\cursos\\data_science\\mitrabajo\\mi_repositorio\\kaggle_maching_learning\\competition\\train_set.csv")

In [3]:
df

0   1  2   3  4  5           6  7  8    9      10    11  \
0      161528   6  a   6  X  2  gynecology  R  F  4.0   45810   2.0   
1      159472  23  a   6  X  4  gynecology  Q  F  2.0  128565  15.0   
2      309765   2  c   5  Z  2  anesthesia  S  F  3.0   46565   5.0   
3      279614  32  f   9  Y  3  gynecology  S  B  4.0  124546   6.0   
4      147791  14  a   1  X  3  gynecology  S  E  2.0   22729   8.0   
...       ...  .. ..  .. .. ..         ... .. ..  ...     ...   ...   
99995  237869  12  a   9  Y  3  gynecology  R  B  3.0   82914   3.0   
99996  254763  28  b  11  X  2  gynecology  R  F  2.0   40026   5.0   
99997   69788   6  a   6  X  3  gynecology  Q  F  3.0   92346   2.0   
99998  204442  32  f   9  Y  2  gynecology  S  B  4.0  113798  15.0   
99999   69647  25  e   1  X  3  gynecology  Q  E  2.0  109237   8.0   

              12        13  14     15      16                  17  
0         Urgent  Moderate   2  21-30  2817.0                0-10  
1         Trauma  Moderate   4  51-60  4498.0               21-30  
2         Urgent  Moderate   2  71-80  4573.0               11-20  
3      Emergency  Moderate   4  11-20  7202.0               51-60  
4         Urgent  Moderate   2  51-60  3398.0               51-60  
...          ...       ...  ..    ...     ...                 ...  
99995  Emergency  Moderate   6  51-60  3966.0  More than 100 Days  
99996     Urgent  Moderate   3  21-30  4005.0               51-60  
99997     Trauma     Minor   2  31-40  5215.0               31-40  
99998     Trauma  Moderate   3  41-50  5092.0               11-20  
99999  Emergency  Moderate   2  41-50  3390.0               41-50  

[100000 rows x 18 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   0       100000 non-null  int64  
 1   1       100000 non-null  int64  
 2   2       100000 non-null  object 
 3   3       100000 non-null  int64  
 4   4       100000 non-null  object 
 5   5       100000 non-null  int64  
 6   6       100000 non-null  object 
 7   7       100000 non-null  object 
 8   8       100000 non-null  object 
 9   9       99967 non-null   float64
 10  10      100000 non-null  int64  
 11  11      98517 non-null   float64
 12  12      100000 non-null  object 
 13  13      100000 non-null  object 
 14  14      100000 non-null  int64  
 15  15      100000 non-null  object 
 16  16      100000 non-null  float64
 17  17      100000 non-null  object 
dtypes: float64(3), int64(6), object(9)
memory usage: 10.3+ MB


In [5]:
df.isnull().sum()

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9       33
10       0
11    1483
12       0
13       0
14       0
15       0
16       0
17       0
dtype: int64

In [6]:
df=df.fillna(0)

In [7]:
#Seleccionopara transformar todas las columnas que son object a numéricas

In [8]:
df.select_dtypes("object").columns.tolist()

['2', '4', '6', '7', '8', '12', '13', '15', '17']

In [9]:
# variable que guarda encoder

In [10]:
le=LabelEncoder()


In [11]:
col_string=df[df.select_dtypes("object").columns].apply(le.fit_transform)

In [12]:
#COLUMNAS QUE SON OBJECT
col_string

2  4  6  7  8  12  13  15  17
0      0  0  2  2  5   2   2   2   0
1      0  0  2  1  5   1   2   5   2
2      2  2  1  3  5   2   2   7   1
3      5  1  2  3  1   0   2   1   5
4      0  0  2  3  4   2   2   5   5
...   .. .. .. .. ..  ..  ..  ..  ..
99995  0  1  2  2  1   0   2   5  10
99996  1  0  2  2  5   2   2   2   5
99997  0  0  2  1  5   1   1   3   3
99998  5  1  2  3  1   1   2   4   1
99999  4  0  2  1  4   0   2   4   4

[100000 rows x 9 columns]

In [13]:
#COLUMNAS QUE SON NUMERICAS
col_num=df.select_dtypes(exclude=["object"])
col_num

0   1   3  5    9      10    11  14      16
0      161528   6   6  2  4.0   45810   2.0   2  2817.0
1      159472  23   6  4  2.0  128565  15.0   4  4498.0
2      309765   2   5  2  3.0   46565   5.0   2  4573.0
3      279614  32   9  3  4.0  124546   6.0   4  7202.0
4      147791  14   1  3  2.0   22729   8.0   2  3398.0
...       ...  ..  .. ..  ...     ...   ...  ..     ...
99995  237869  12   9  3  3.0   82914   3.0   6  3966.0
99996  254763  28  11  2  2.0   40026   5.0   3  4005.0
99997   69788   6   6  3  3.0   92346   2.0   2  5215.0
99998  204442  32   9  2  4.0  113798  15.0   3  5092.0
99999   69647  25   1  3  2.0  109237   8.0   2  3390.0

[100000 rows x 9 columns]

In [14]:
#Uno en un DataFrame

In [15]:
df=pd.concat([col_string,col_num],axis=1)

In [16]:
df

2  4  6  7  8  12  13  15  17       0   1   3  5    9      10    11  \
0      0  0  2  2  5   2   2   2   0  161528   6   6  2  4.0   45810   2.0   
1      0  0  2  1  5   1   2   5   2  159472  23   6  4  2.0  128565  15.0   
2      2  2  1  3  5   2   2   7   1  309765   2   5  2  3.0   46565   5.0   
3      5  1  2  3  1   0   2   1   5  279614  32   9  3  4.0  124546   6.0   
4      0  0  2  3  4   2   2   5   5  147791  14   1  3  2.0   22729   8.0   
...   .. .. .. .. ..  ..  ..  ..  ..     ...  ..  .. ..  ...     ...   ...   
99995  0  1  2  2  1   0   2   5  10  237869  12   9  3  3.0   82914   3.0   
99996  1  0  2  2  5   2   2   2   5  254763  28  11  2  2.0   40026   5.0   
99997  0  0  2  1  5   1   1   3   3   69788   6   6  3  3.0   92346   2.0   
99998  5  1  2  3  1   1   2   4   1  204442  32   9  2  4.0  113798  15.0   
99999  4  0  2  1  4   0   2   4   4   69647  25   1  3  2.0  109237   8.0   

       14      16  
0       2  2817.0  
1       4  4498.0  
2       2  4573.0  
3       4  7202.0  
4       2  3398.0  
...    ..     ...  
99995   6  3966.0  
99996   3  4005.0  
99997   2  5215.0  
99998   3  5092.0  
99999   2  3390.0  

[100000 rows x 18 columns]

In [17]:
#ORDENO EL DATAFRAME

In [18]:
df1 = df[['5','6','7','8','9','10','12','13','14','15','16','17']]
df1

5  6  7  8    9      10  12  13  14  15      16  17
0      2  2  2  5  4.0   45810   2   2   2   2  2817.0   0
1      4  2  1  5  2.0  128565   1   2   4   5  4498.0   2
2      2  1  3  5  3.0   46565   2   2   2   7  4573.0   1
3      3  2  3  1  4.0  124546   0   2   4   1  7202.0   5
4      3  2  3  4  2.0   22729   2   2   2   5  3398.0   5
...   .. .. .. ..  ...     ...  ..  ..  ..  ..     ...  ..
99995  3  2  2  1  3.0   82914   0   2   6   5  3966.0  10
99996  2  2  2  5  2.0   40026   2   2   3   2  4005.0   5
99997  3  2  1  5  3.0   92346   1   1   2   3  5215.0   3
99998  2  2  3  1  4.0  113798   1   2   3   4  5092.0   1
99999  3  2  1  4  2.0  109237   0   2   2   4  3390.0   4

[100000 rows x 12 columns]

In [19]:
df2=df1.iloc[:,0:-1]


In [20]:
X=df1.iloc[:,0:11]
X

5  6  7  8    9      10  12  13  14  15      16
0      2  2  2  5  4.0   45810   2   2   2   2  2817.0
1      4  2  1  5  2.0  128565   1   2   4   5  4498.0
2      2  1  3  5  3.0   46565   2   2   2   7  4573.0
3      3  2  3  1  4.0  124546   0   2   4   1  7202.0
4      3  2  3  4  2.0   22729   2   2   2   5  3398.0
...   .. .. .. ..  ...     ...  ..  ..  ..  ..     ...
99995  3  2  2  1  3.0   82914   0   2   6   5  3966.0
99996  2  2  2  5  2.0   40026   2   2   3   2  4005.0
99997  3  2  1  5  3.0   92346   1   1   2   3  5215.0
99998  2  2  3  1  4.0  113798   1   2   3   4  5092.0
99999  3  2  1  4  2.0  109237   0   2   2   4  3390.0

[100000 rows x 11 columns]

In [21]:
X=np.array(X)
X

array([[2.000e+00, 2.000e+00, 2.000e+00, ..., 2.000e+00, 2.000e+00,
        2.817e+03],
       [4.000e+00, 2.000e+00, 1.000e+00, ..., 4.000e+00, 5.000e+00,
        4.498e+03],
       [2.000e+00, 1.000e+00, 3.000e+00, ..., 2.000e+00, 7.000e+00,
        4.573e+03],
       ...,
       [3.000e+00, 2.000e+00, 1.000e+00, ..., 2.000e+00, 3.000e+00,
        5.215e+03],
       [2.000e+00, 2.000e+00, 3.000e+00, ..., 3.000e+00, 4.000e+00,
        5.092e+03],
       [3.000e+00, 2.000e+00, 1.000e+00, ..., 2.000e+00, 4.000e+00,
        3.390e+03]])

In [22]:
y=df1.iloc[:,-1]
y

0         0
1         2
2         1
3         5
4         5
         ..
99995    10
99996     5
99997     3
99998     1
99999     4
Name: 17, Length: 100000, dtype: int32

In [23]:
y=np.array(y)
y

array([0, 2, 1, ..., 3, 1, 4])

In [24]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [25]:
predictions = model.predict(X)
print(predictions)

[2 2 2 ... 2 2 2]


In [26]:
model.score(X,y)

0.27452

In [27]:
validation_size = 0.30
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=validation_size, random_state=seed)

In [66]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=30, random_state=seed) #Parte los datos en 30 trozos para usar validación cruzada / cross validation
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(cv_results)
print(msg)

[0.27335047 0.27806341 0.27549272 0.2823479  0.28020566 0.26735219
 0.26606684 0.2823479  0.27806341 0.28191945 0.26575225 0.27732533
 0.28418345 0.26532362 0.26789541 0.26875268 0.27132447 0.26575225
 0.26103729 0.28118303 0.27732533 0.27646807 0.28889841 0.27775396
 0.28118303 0.27303901 0.26703815 0.27346764 0.26403772 0.27989713]
Logistic Regression: 0.274428 (0.007033)


In [67]:
predictions = model.predict(X_test)
print(accuracy_score(Y_test, predictions))

0.27466666666666667


In [68]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 27.47 %
Error: 72.53 %


In [69]:
to_pred = pd.read_csv("C:\\Users\\JoseMaría\\Documents\\cursos\\data_science\\mitrabajo\\mi_repositorio\\kaggle_maching_learning\\competition\\test_set.csv")

In [70]:
to_pred

0   1  2   3  4  5                   6  7  8    9      10    11  \
0       314114  19  a   7  Y  4          gynecology  S  C  2.0   59278   8.0   
1       208989  15  c   5  Z  3          gynecology  S  F  2.0  102253  15.0   
2       305872  17  e   1  X  4          gynecology  R  E  4.0    5828   4.0   
3       266099   3  c   3  Z  4  TB & Chest disease  R  A  2.0   56642   9.0   
4        13228   6  a   6  X  4          gynecology  R  F  1.0  116266   8.0   
...        ...  .. ..  .. .. ..                 ... .. ..  ...     ...   ...   
133739  318155  18  d  13  Y  6          anesthesia  Q  B  3.0  123269  25.0   
133740  144850  27  a   7  Y  2          gynecology  S  C  2.0    1293   8.0   
133741  180676  16  c   3  Z  3          gynecology  R  A  3.0  112921   5.0   
133742   39933  28  b  11  X  4          gynecology  R  F  2.0     585   2.0   
133743  116673   6  a   6  X  4  TB & Chest disease  Q  F  2.0  119482  12.0   

               12        13  14     15      16  
0       Emergency     Minor   2  41-50  4778.0  
1          Trauma  Moderate   3  31-40  5734.0  
2       Emergency     Minor   3  71-80  5064.0  
3          Urgent   Extreme   4  31-40  3254.0  
4       Emergency     Minor   3  21-30  4639.0  
...           ...       ...  ..    ...     ...  
133739     Urgent     Minor   4  51-60  5089.0  
133740  Emergency  Moderate   3  61-70  6713.0  
133741     Trauma     Minor   3  31-40  5326.0  
133742     Trauma   Extreme   2  31-40  7072.0  
133743     Trauma  Moderate   4  51-60  5221.0  

[133744 rows x 17 columns]

In [71]:
to_pred.select_dtypes("object").columns.tolist()

['2', '4', '6', '7', '8', '12', '13', '15']

In [72]:
col_string1=to_pred[to_pred.select_dtypes("object").columns].apply(LabelEncoder().fit_transform)
col_string1

2  4  6  7  8  12  13  15
0       0  1  2  3  2   0   1   4
1       2  2  2  3  5   1   2   3
2       4  0  2  2  4   0   1   7
3       2  2  0  2  0   2   0   3
4       0  0  2  2  5   0   1   2
...    .. .. .. .. ..  ..  ..  ..
133739  3  1  1  1  1   2   1   5
133740  0  1  2  3  2   0   2   6
133741  2  2  2  2  0   1   1   3
133742  1  0  2  2  5   1   0   3
133743  0  0  0  1  5   1   2   5

[133744 rows x 8 columns]

In [73]:
col_num1=to_pred.select_dtypes(exclude=["object"])
col_num1

0   1   3  5    9      10    11  14      16
0       314114  19   7  4  2.0   59278   8.0   2  4778.0
1       208989  15   5  3  2.0  102253  15.0   3  5734.0
2       305872  17   1  4  4.0    5828   4.0   3  5064.0
3       266099   3   3  4  2.0   56642   9.0   4  3254.0
4        13228   6   6  4  1.0  116266   8.0   3  4639.0
...        ...  ..  .. ..  ...     ...   ...  ..     ...
133739  318155  18  13  6  3.0  123269  25.0   4  5089.0
133740  144850  27   7  2  2.0    1293   8.0   3  6713.0
133741  180676  16   3  3  3.0  112921   5.0   3  5326.0
133742   39933  28  11  4  2.0     585   2.0   2  7072.0
133743  116673   6   6  4  2.0  119482  12.0   4  5221.0

[133744 rows x 9 columns]

In [74]:
to_pred=pd.concat([col_string1,col_num1],axis=1)
to_pred

2  4  6  7  8  12  13  15       0   1   3  5    9      10    11  14  \
0       0  1  2  3  2   0   1   4  314114  19   7  4  2.0   59278   8.0   2   
1       2  2  2  3  5   1   2   3  208989  15   5  3  2.0  102253  15.0   3   
2       4  0  2  2  4   0   1   7  305872  17   1  4  4.0    5828   4.0   3   
3       2  2  0  2  0   2   0   3  266099   3   3  4  2.0   56642   9.0   4   
4       0  0  2  2  5   0   1   2   13228   6   6  4  1.0  116266   8.0   3   
...    .. .. .. .. ..  ..  ..  ..     ...  ..  .. ..  ...     ...   ...  ..   
133739  3  1  1  1  1   2   1   5  318155  18  13  6  3.0  123269  25.0   4   
133740  0  1  2  3  2   0   2   6  144850  27   7  2  2.0    1293   8.0   3   
133741  2  2  2  2  0   1   1   3  180676  16   3  3  3.0  112921   5.0   3   
133742  1  0  2  2  5   1   0   3   39933  28  11  4  2.0     585   2.0   2   
133743  0  0  0  1  5   1   2   5  116673   6   6  4  2.0  119482  12.0   4   

            16  
0       4778.0  
1       5734.0  
2       5064.0  
3       3254.0  
4       4639.0  
...        ...  
133739  5089.0  
133740  6713.0  
133741  5326.0  
133742  7072.0  
133743  5221.0  

[133744 rows x 17 columns]

In [75]:
to_pred = to_pred[['0','5','6','7','8','9','10','12','13','14','15','16']]
to_pred

0  5  6  7  8    9      10  12  13  14  15      16
0       314114  4  2  3  2  2.0   59278   0   1   2   4  4778.0
1       208989  3  2  3  5  2.0  102253   1   2   3   3  5734.0
2       305872  4  2  2  4  4.0    5828   0   1   3   7  5064.0
3       266099  4  0  2  0  2.0   56642   2   0   4   3  3254.0
4        13228  4  2  2  5  1.0  116266   0   1   3   2  4639.0
...        ... .. .. .. ..  ...     ...  ..  ..  ..  ..     ...
133739  318155  6  1  1  1  3.0  123269   2   1   4   5  5089.0
133740  144850  2  2  3  2  2.0    1293   0   2   3   6  6713.0
133741  180676  3  2  2  0  3.0  112921   1   1   3   3  5326.0
133742   39933  4  2  2  5  2.0     585   1   0   2   3  7072.0
133743  116673  4  0  1  5  2.0  119482   1   2   4   5  5221.0

[133744 rows x 12 columns]

In [76]:
to_pred.isnull().sum()

0      0
5      0
6      0
7      0
8      0
9     40
10     0
12     0
13     0
14     0
15     0
16     0
dtype: int64

In [77]:
to_pred = to_pred.fillna(0)

In [78]:
predictions_submit = model.predict(to_pred[['5','6','7','8','9','10','12','13','14','15','16']])
predictions_submit

array([2, 2, 2, ..., 2, 2, 2])

In [79]:
predictions_submit2=le.inverse_transform(predictions_submit)

In [80]:
predictions_submit2

array(['21-30', '21-30', '21-30', ..., '21-30', '21-30', '21-30'],
      dtype=object)

In [90]:
submission_lr=pd.DataFrame({"id": to_pred["0"],"days":predictions_submit2})
submission_lr

id   days
0       314114  21-30
1       208989  21-30
2       305872  21-30
3       266099  21-30
4        13228  21-30
...        ...    ...
133739  318155  21-30
133740  144850  21-30
133741  180676  21-30
133742   39933  21-30
133743  116673  21-30

[133744 rows x 2 columns]

In [87]:
sample = pd.read_csv("C:\\Users\\JoseMaría\\Documents\\cursos\\data_science\\mitrabajo\\mi_repositorio\\kaggle_maching_learning\\competition\\sample_submission.csv")

In [91]:
sample.shape

(133744, 2)

In [92]:
if submission_lr.shape == sample.shape:
    if submission_lr.columns.all() == sample.columns.all():
        if submission_lr.id.all() == sample.id.all():
            print("you're ready to submit!")
            submission_lr.to_csv("to_submit.csv", index = False)

you're ready to submit!
