1. 

(X_train=80%)
(X_test=20%)

A partir del archivo "iris.csv" que se corresponde con datos relacionados con tres tipos de plantas (el target es el tipo de planta):

- Mediante regresión logística, predice qué planta se corresponde con los ejemplos: [[15.7,2.8,9.5,0.1]] y [[1.7,3.8,4.5,11.3]]
- ¿Qué acierto tiene tu modelo? (score)
- Utiliza un conjunto de test con el 40% de los datos: ¿cambian los resultados anteriores? ¿por qué?
- Elimina la clase "Virginica" de tus datos. Repite el proceso anterior, ¿cambian los resultados?
- ¿Consideras la regresión logística un buen algoritmo para estos datos? ¿por qué?

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [2]:
data=pd.read_csv('../data/iris.csv')
data

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
variety=data.iloc[:,-1]
variety

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [4]:
sepal_length=data.iloc[:,0]
sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal.length, Length: 150, dtype: float64

In [5]:
sepal_width=data.iloc[:,1]
sepal_width

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: sepal.width, Length: 150, dtype: float64

In [6]:
petal_length=data.iloc[:,2]
petal_length

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal.length, Length: 150, dtype: float64

In [7]:
petal_width=data.iloc[:,3]
petal_width

0      0.2
1      0.2
2      0.2
3      0.2
4      0.2
      ... 
145    2.3
146    1.9
147    2.0
148    2.3
149    1.8
Name: petal.width, Length: 150, dtype: float64

In [8]:
#CREO MI X UNIENDO TODAS LAS COLUMNAS DEL DATAFRAME EXCEPTO LA DE TARGET EN UN ARRAY
X=np.array(list(zip(sepal_length,sepal_width,petal_length,petal_width)))


In [9]:
y=variety
dataframe=data
y=np.array(dataframe['variety'])


In [10]:
model = linear_model.LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [11]:
# PARTIMOS CON 20% DATOS DE TEST
seed = 7
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.20, random_state=seed)

In [12]:
predictions = model.predict(X_test)
print(accuracy_score(y_test, predictions))

0.9


In [13]:
acierto = accuracy_score(y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 90.0 %
Error: 10.0 %


In [14]:
y_test.shape

(30,)

In [15]:
print(confusion_matrix(y_test, predictions))

[[ 7  0  0]
 [ 0 10  2]
 [ 0  1 10]]


In [16]:
predicted = model.predict([[15.7,2.8,9.5,0.1]]) 
print(predicted)

['Virginica']


In [17]:
predicted = model.predict([[1.7,3.8,4.5,11.3]]) 
print(predicted)

['Virginica']


In [18]:
#AHORA 40% DATOS CONJUNTO TEST $$$$$$$$$$$$$$ SUBE ACIERTO

In [19]:
seed = 7
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.4, random_state=seed)

In [20]:
predictions = model.predict(X_test)
print(accuracy_score(y_test, predictions))

0.95


In [21]:
acierto = accuracy_score(y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 95.0 %
Error: 5.0 %


In [22]:
y_test.shape

(60,)

In [23]:
print(confusion_matrix(y_test, predictions))

[[19  0  0]
 [ 0 19  2]
 [ 0  1 19]]


In [24]:
#ELIMINO VIRGINICA

In [25]:
Y=y[0:100]
Y.shape

(100,)

In [26]:
x=X[0:100]
x.shape


(100, 4)

In [27]:
model = linear_model.LogisticRegression()
model.fit(x,Y)

LogisticRegression()

In [28]:
seed = 7
x_train, x_test, Y_train, Y_test = model_selection.train_test_split(x, Y, test_size=0.4, random_state=seed)

In [29]:
predictions=model.predict(x_test)
print(accuracy_score(Y_test, predictions))

1.0


In [30]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 100.0 %
Error: 0.0 %


In [31]:
Y_test.shape

(40,)

In [32]:
print(confusion_matrix(Y_test, predictions))

[[22  0]
 [ 0 18]]


In [33]:
# CONSIGO UN 100% DE ACIERTO CON UN 40% DE DATOS PARA TEXT Y UNA CLASE MENOS.

In [34]:
# CON UNA CLASE MAS Y EL MISMO PORCENTAJE ME DA UN 95% DE ACIERTO.

In [35]:
#MODELO FIABLE